version: "3"

services:
  postgres-service:
    image: postgres:15
    restart: always
    container_name: "${PROJECT_NAME}-postgres"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  app:
    build: .
    container_name: "${PROJECT_NAME}"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-service
    restart: always
